version: "3.8"

networks:
  local:
    driver: bridge

services:
  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass password
    ports:
      - 6379:6379

  ws-proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: ws-proxy
    ports:
      - 5555:5555
    environment:
      - PORT=5555
      - ORIGIN_SOURCE=localhost:3000
      - LOKI_URL=
      - LOKI_USERNAME=
      - LOKI_PASSWORD=

  bot:
    build:
      context: ./discordbot
      dockerfile: Dockerfile.dev
    container_name: bot
    depends_on:
      - ws-proxy
      - redis
    environment:
      - REDISHOST=redis
      - REDISPASSWORD=password
      - REDISPORT=6379
      - REDISUSER=default
      - WEBSOCKET_HOST=ws-proxy:5555
      - DISCORD_TOKEN=
      - LOKI_URL=
      - LOKI_USERNAME=
      - LOKI_PASSWORD=
    volumes:
      - ./discordbot:/app
      - ./discordbot/data:/app/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    depends_on:
      - redis
    ports:
      - 3000:3000
    environment:
      - REDISHOST=redis
      - REDISPASSWORD=password
      - REDISPORT=6379
      - REDISUSER=default
      - PUBLIC_WEBSOCKET_PROXY=localhost:5555
      - LOKI_URL=
      - LOKI_USERNAME=
      - LOKI_PASSWORD=
    volumes:
      - ./frontend:/app
      - /app/node_modules
