version: "3.8"

networks:
  local:
    driver: bridge

services:
  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass password
    ports:
      - 6379:6379

  websocket:
    build:
      context: ./pubsub
      dockerfile: Dockerfile.dev
    container_name: websocket
    ports:
      - 5555:5555
    environment:
      - PORT=5555
    volumes:
      - ./pubsub:/app
      - /app/node_modules

  bot:
    build:
      context: ./discordbot
      dockerfile: Dockerfile.dev
    container_name: bot
    depends_on:
      - websocket
      - redis
    environment:
      - REDISHOST=redis
      - REDISPASSWORD=password
      - REDISPORT=6379
      - REDISUSER=default
    volumes:
      - ./discordbot:/app
      - ./discordbot/data:/app/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    depends_on:
      - redis
    ports:
      - 3000:3000
    environment:
      - REDISHOST=redis
      - REDISPASSWORD=password
      - REDISPORT=6379
      - REDISUSER=default
    volumes:
      - ./frontend:/app
      - /app/node_modules
