[package]
name = "proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
actix-web-actors = "4.0"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["websocket"] }
dotenv = "0.15"
